### ISSUE TITLE
Problem with perl-reversion

### ISSUE THREAD

**Issue by hadjiprocopis** [briandfoy/perl-version#11]
When running ```perl-reversion``` I get this error:

```
Odd number of elements in hash assignment at /opt/perlbrew/perls/perl-5.38.2/bin/perl-reversion line 502.
Unknown PerlIO layer "binmode" at /opt/perlbrew/perls/perl-5.38.2/bin/perl-reversion line 506.
...
```

In the source of said script

https://metacpan.org/release/BDFOY/Perl-Version-1.016/source/examples/perl-reversion#L492

there is this call:

```
      lines => read_lines( $doc, binmode => ':raw', array_ref => 1 ),
```

I think it should be 
```
      lines => read_lines( $doc, ':raw', array_ref => 1 ),
```

with this change, script works fine for me  (perl 5.38.2)

**Comment by briandfoy** [comment]
Released as 1.017. Thanks,
