### ISSUE TITLE
RT #110074: 5.011 == 5.11 in 1.013

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/perl-version#7]
From Gabor in [#110074 on rt.cpan.org](https://rt.cpan.org/Ticket/Display.html?id=110074):

Using Perl::Version 1.013 I got that this

    Perl::Version->new('5.011') == Perl::Version->new('5.11')

returns true.

Is that the expected behavior?

**Comment by briandfoy** [comment]
I added _t/99.rt-110074.t_ for this, and I updated the docs.

I think this is the expected behavior based on how Perl (the project) and CPAN treat version numbers. If this were a general version module for the entire Internet, I would say this is wrong.

**Comment by Grinnz** [comment]
This is not how Perl and CPAN treat version numbers, and why Perl::Version has not been suitable for me to bump version numbers. See https://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html - these are treated as decimal (float) versions by Perl.

**Comment by briandfoy** [comment]
Yes, you are right. It pads in groups of three on the other side.

But, this is what Perl::Version does, and without a major version bump to break that behavior, this is what it's going to keep doing. I didn't write this stuff, it's a pain to deal with, and I'm not going to rewrite it. There are lots of other broken things too.
