### ISSUE TITLE
RT #124070: Behavior do not correspond documentation

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/perl-version#9]
From KES in [#124070 on rt.cpan.org](https://rt.cpan.org/Ticket/Display.html?id=124070)

Perl-Version-1.013.tar.gz

    $ perl -MPerl::Version -e 'print Perl::Version->new( '5.008007_01' )->normal;'
    v5.8.7.1

DOC:

    my $version = Perl::Version->new( '5.008007_01' );
    print $version->normal, "\n";

prints

    v5.8.7_001

**Comment by briandfoy** [comment]
I couldn't reproduce this behavior. I'm getting the same `v5.8.7_01` for both 1.013 and the latest version. There is one too many zeros in the example output because Perl::Version tries to match the number of digits after the `_` for a string argument. I'll fix the docs for that.

I noticed that there's a quoting problem in your command line since you use single quotes inside the single quotes. Note that a number argument with an underscore is different because perl has already parsed the numeric literal so that the `_` isn't part of the value. As such, the last `01` is zero left padded to get `001`, and as the fourth part of semantic versioning, you get the string you report:

    $ perl -MPerl::Version -e "print Perl::Version->new( 5.008007_01 )->normal;"
    v5.8.7.1

If there's something different going on you can re-open this issue or start a new one.

**Comment by KES777** [comment]
@briandfoy I think this section should be highlighted in sysnopsis: https://metacpan.org/pod/Perl::Version#Real-Numbers

And this section should be simplified: https://metacpan.org/pod/Perl::Version#new
I should not use `->inc_version` in description. It is too complex to follow two things at once. It would be better to have just:
```perl
for my $v ( @version ) {
    print Perl::Version->new( $v ), "\n";
}
```
with real numbers examples:
```diff
my @version = (
    '1.3.0',    'v1.03.00',     '1.10.03', '2.00.00',
    '1.2',      'v1.2.3.4.5.6', 'v1.2',    'Revision: 3.0',
    '1.001001', '1.001_001',    '3.0.4_001',
    1.001001, 1.001_001,    1.001_01
    
);
```

**Comment by briandfoy** [comment]
Perhaps you can supply a patch that shows what you want this to be.

I don't see the problem with the explanation under Real Numbers. Unless I'm missing something, this is still a problem with basic Perl literals. (It helps in reports not to use "this" or similar language because we probably think it refers to different things). 

The example in `new` is correct according to what Perl::Version wants to do. I'd like to see what you'd change it to. 

But, please open a different issue for that since it's unrelated to this issue.
